### ISSUE TITLE
Product Data using API Call instead of local JSON files to display products

### ISSUE THREAD

**Issue by Farial-mahmod** [Djallil14/SwiftUI-FakeShopping-App#5]
Hello, thanks for this shopping project. My suggestion is that implementing API calls (URLSession, Alamofire etc.) would be more advantageous to fetch products than locally storing JSON files to display products.

**Comment by Djallil14** [comment]
Hello i hadn't update or even checked the project for a while (i'm pretty busy) but it does API calls, the local JSON is only for preview. here is the api calls using URLSession :).
 https://github.com/Djallil14/SwiftUI-FakeShopping-App/blob/main/ModerneShopping/ViewModel/APIServices.swift

**Comment by Farial-mahmod** [comment]
Thanks for the update and the link. This one is much better to learn than loading local JSONs :)

**Comment by Djallil14** [comment]
It was always there, no update has been done haha but not problem enjoy :)
